
export const SET_SEARCH_INPUT = 'SET_SEARCH_INPUT';
export const RESULTS_FETCHED = 'RESULTS_FETCHED';
export const INFINITE_SCROLL_RESULTS_FETCHED = 'INFINITE_SCROLL_RESULTS_FETCHED';
export const REVIEWS_FETCHED = 'REVIEWS_FETCHED';
